FROM nginx:alpine

RUN apk add --no-cache wget unzip

ARG GITHUB_REPO=CodeFuckee/mobile_portainer_flutter_module
# GitHub 标准 latest release 下载链接
ARG DOWNLOAD_BASE=https://github.com

RUN wget -O /tmp/web-build.zip \
    "${DOWNLOAD_BASE}/${GITHUB_REPO}/releases/latest/download/web-build.zip" && \
    unzip -o /tmp/web-build.zip -d /usr/share/nginx/html && \
    rm /tmp/web-build.zip

COPY nginx.web.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
