platform :osx, '10.15'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!
  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
  # Include AppInfo.xcconfig in each Pods-Runner config so that
  # PRODUCT_NAME and PRODUCT_BUNDLE_IDENTIFIER are available.
  ['debug', 'release', 'profile'].each do |config|
    xcconfig_path = File.join('Pods', 'Target Support Files', 'Pods-Runner', "Pods-Runner.#{config}.xcconfig")
    if File.exist?(xcconfig_path)
      content = File.read(xcconfig_path)
      include_line = '#include "../../../Runner/Configs/AppInfo.xcconfig"'
      unless content.include?(include_line)
        File.open(xcconfig_path, 'a') { |f| f.puts "\n#{include_line}" }
      end
    end
  end
end
